FROM node:16

# Switch to archive repos as the repos have been archived and removed from the original addresses
RUN set -eux; \
  echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until; \
  sed -i \
    -e 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' \
    -e 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' \
    -e 's|http://deb.debian.org/debian-security|http://archive.debian.org/debian-security|g' \
    /etc/apt/sources.list || true; \
  if ls /etc/apt/sources.list.d/*.list >/dev/null 2>&1; then \
    sed -i \
      -e 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' \
      -e 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' \
      -e 's|http://deb.debian.org/debian-security|http://archive.debian.org/debian-security|g' \
      /etc/apt/sources.list.d/*.list; \
  fi

RUN apt-get update && \
  apt-get -y install nasm zlib1g build-essential \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app && chown -R node /app

USER node

WORKDIR /app

COPY --chown=node package.json /app/
COPY --chown=node package-lock.json /app/

RUN npm ci --legacy-peer-deps

COPY --chown=node . /app

RUN npm run build

EXPOSE 9000

CMD [ "npm", "run", "serve", "--", "--host", "0.0.0.0" ]
